### PR TITLE
Kibana 44

### PR DESCRIPTION
**Pull request by krallin**
@fancyremarker (@aaw),

(view https://github.com/aptible/docker-elasticsearch/pull/17 for context)

This tweaks the image to install both Kibana 4.1 and 4.4, and allows the user to set `ACTIVE_KIBANA_VERSION` to 41 or 44 to choose the one they want.

However, that shouldn't be needed (!), because this also auto-detects the Elasticsearch version at startup (by hitting `DATABASE_URL`) and selects the appropriate Kibana version accoridngly (4.1 for ES 1.x, 4.4 for ES 2.x).

This makes the image slightly heavier, but I think it's worth it from a usability perspective.

I'm a little concerned about including all the tests in the image (same topic discussed in https://github.com/aptible/docker-logstash/pull/1#issuecomment-174577262). They tend to be a little flaky when run on my staging environment (`timeout 1` isn't always enough for Nginx to start), and adding _more_ tests ad I did in this PR increases the probability that at least one of them will fail, killing the deploy for no apparent reason (this has happened to me). Thoughts? We could use Travis to run the build and run the tests separately.
## 

Note: I also included a few fixes to `run-kibana.sh` in a separate commit. Those aren't strictly speaking necessary, but I think they're worth including.

### CODE REVIEW

**Comment by fancyremarker** [comment]
I really like the concept behind this, and think the increase in image size is justified by the confusion it spares customers from.

**Comment by fancyremarker** [comment]
> We could use Travis to run the build and run the tests separately.

I'm for that.

**Comment by krallin** [comment]
Added the Travis scaffolding; tests no longer run at build time (they run in Travis instead).

**Comment by krallin** [comment]
I also disabled the build trigger in Quay. While this repo _can_ be built in Quay, I think it's better to ensure only images that have in fact been tested are published there :)

**Pull request merged**
