### PR TITLE
Upgrading to Kibana 4

### PR DESCRIPTION
**Pull request by tobalsgithub**
Note that Kibana 4 requires Elasticsearch 1.4.4 or higher. I've updated the ES image here: https://github.com/aptible/docker-elasticsearch/pull/5

Kibana 4 is much different than Kibana 3. It is a java applet, rather than just static html and js files, and the connection to elasticsearch is done through the java applet, rather than straight from the browser. 

This has a couple interesting effects. 
1. Testing responses from kibana becomes very difficult, given that kibana actually tries to initiate a connection with an elasticsearch server. Rather than testing responses from Kibana, I added tests that ensure the kibana.yml file is setup correctly, and trust that kibana is tested fully by their team.
2. Since the connection to ES is done via the java applet, the username and password of the ES database must be defined in the kibana.yml config file. I chose to do this by specifying the DATABASE_URL environment variable in http://user:pass@ip:port format. This could easily be split out into separate environment variables. 
3. The nginx setup becomes slightly simpler, where all we have to do is proxy requests to the kibana server running on port 5601.

### CODE REVIEW

**Comment by aaw** [comment]
Wow, thanks for all this work, @tobalsgithub! Give me a few days to make some time to thoroughly test this, make sure it and the new ES image run on Aptible, and make sure that the traffic is still proxied correctly through the user-level NGiNX instance. I'll update once I've done that.

**Comment by tobalsgithub** [comment]
Cool. Let me know if you hit any issues or want some help debugging/testing.

**Comment by fancyremarker** [comment]
This is great, @tobalsgithub — thanks! Because of a bug in the latest release of Kibana (elastic/kibana#3302), this broke our use of the `AUTH_CREDENTIALS` environment variable to configure HTTP Basic Auth; basically, in the latest release (4.0.2), any HTTP Basic Auth credentials passed to Kibana would be proxied through to Elasticsearch — so it was necessary to use the same credentials for Kibana as for the Elasticsearch database itself, which is not optimal.

As a result, I've rebased this and upgraded to 4.1.0-snapshot in #7. You can check out and deploy that branch to use Kibana 4 on Aptible (note that it will require an Elasticsearch 1.5 database). After the bug fix makes it into a stable release, we'll merge this `v4.10.0-snapshot` branch into master.

cc: @Fluidbyte @mjacksonw

**Comment by mjacksonw** [comment]
Awesome – looking forward to checking this out. Thanks @tobalsgithub!

**Comment by tobalsgithub** [comment]
This proved slightly more tricky than anticipated, but I got it working.

First, the sha changes with each commit to kibana master, so that has to be updated. I cloned this repo and simply took out the sha check for now.

But second, even without the sha check, there seems to be an issue with the .tar.gz file from elasticsearch, at least currently. The build is failing with 

```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

To get around this, I used the following Dockerfile using the .zip file instead of the tar:

```
FROM quay.io/aptible/ubuntu:14.04

# Install NGiNX.
RUN apt-get update && \
    apt-get install -y software-properties-common \
    python-software-properties && \
    add-apt-repository -y ppa:nginx/stable && apt-get update && \
    apt-get -y install curl ucspi-tcp apache2-utils nginx ruby

# Install unzip
RUN apt-get install -y unzip

# Download Kibana 4.1.0, extract into /opt/kibana-4.1.0.
RUN curl -O http://download.elastic.co/kibana/kibana/kibana-4.1.0-snapshot-linux-x64.zip && \
    unzip kibana-4.1.0-snapshot-linux-x64.zip -d /opt

# Overwrite default nginx config with our config.
RUN rm /etc/nginx/sites-enabled/*
ADD templates/sites-enabled /
RUN rm /opt/kibana-4.1.0-snapshot-linux-x64/config/kibana.yml
ADD templates/opt/kibana-4.1.0/ /

# Add script that starts NGiNX in front of Kibana and tails the NGiNX access/error logs.
ADD bin .
RUN chmod 700 ./run-kibana.sh

# Run tests.
ADD test /tmp/test
RUN bats /tmp/test

EXPOSE 80

CMD ["./run-kibana.sh"]
```

I also updated my Procfile to

```
web: ./run-kibana.sh
```

in order to get a default host.

**Comment by fancyremarker** [comment]
@tobalsgithub: Thanks a ton for that detailed rundown — are you able to create a pull request with your changes, onto the base branch `v4.10.0-snapshot`?

**Comment by tobalsgithub** [comment]
Pull request with updates: https://github.com/aptible/docker-kibana/pull/8

**Pull request closed without merging**
